# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 41c5a734f66b486b800ae86c464364d9becb8c6412a52f171c3e47fc4bbe57162578d819077da2e00824de16c5395fd360888463e69171545f0fcde2c45ee09e

test:
  secret_key_base: e0e0b04da241518d427ec88036b29848e6a272dfdaaff628954bac7f1c880fe87931e42e1c01c05a2edde6a2af02d5ac2a067df6ed7485dec3dfd82d55fd0e88

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
